services:
  ros_praxis:
    build: .
    network_mode: host
    privileged: true
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
      - "/dev/ttyACM1:/dev/ttyACM1"
    volumes:
      - .:/workspace/praxis-core
      - ./calibration:/workspace/praxis-core/calibration
    working_dir: /workspace/praxis-core
    environment:
      - ROS_DOMAIN_ID=0
      - HF_LEROBOT_CALIBRATION=/workspace/praxis-core/calibration
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    stdin_open: true
    tty: true
    command: bash
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

