# @package sensor

_target_: praxis.sensing.digit.DigitSensor
config:
  # Sensor metadata
  name: 'sensorR'
  sample_rate: 15.0  # Hz
  timeout: 1.0  # seconds
  auto_start: true
  id: '-1'
  # Camera device configuration
  device_name: "DIGIT"  
  # Desired output image dimensions
  imgh: 240  # Output image height
  imgw: 320  # Output image width
  
