# @package robot

_target_: praxis.robots.so101real.SO101Real

config:
  name: "piplup"
  dof: 6
  
  #Robot connection port
  port: "/dev/ttyACM2"
  calibration: "/home/Shared/calibration/robots/so101_follower/"

  id: "piplup_follower"
  init_joint_positions: [1.5708, -1.5708, 1.5708, -1.5708, -1.5708, 0]
  joint_limits_lower: [-6.2832, -6.2832, -6.2832, -6.2832, -6.2832, -6.2832]
  joint_limits_upper: [6.2832, 6.2832, 6.2832, 6.2832, 6.2832, 6.2832]

  enable_viewer: false
  viewer_fps: 30.0