# @package robot

_target_: praxis.robots.so101sim.SO101Sim
config:
  xml_path: "so101/mjcf/so101_new_calib.xml"
  actuator_names: ["shoulder_pan", "shoulder_lift", "elbow_flex", "wrist_flex", "wrist_roll", "gripper"]
  joint_names: ["shoulder_pan", "shoulder_lift", "elbow_flex", "wrist_flex", "wrist_roll", "gripper"]
  body_names: ["base", "shoulder", "upper_arm", "lower_arm", "wrist", "gripper", "moving_jaw_so101_v1"]
  ee_site_name: "gripperframe"

  name: "so101sim"
  dof: 6
  init_joint_positions: [1.5708, -1.5708, 1.5708, -1.5708, -1.5708, 0]
  joint_limits_lower: [-3.1416, -3.1416, -3.1416, -3.1416, -3.1416, -3.1416]
  joint_limits_upper: [3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416]

  sim_dt: 0.002
  gravity_compensation: true
  enable_viewer: true
  viewer_fps: 45.0
  integration_dt: 1.0
  damping: 1e-4
  max_angvel: 0.0
