# @package robot

_target_: praxis.robots.so101real.SO101Real

config:
  name: "so101real"
  dof: 6
  
  #Robot connection port
  port: "/dev/ttyACM1"
  calibration: "/workspace/praxis-core/calibration/robots/so101_follower/"

  id: "follower_arm"
  init_joint_positions: [1.5708, -1.5708, 1.5708, -1.5708, -1.5708, 0]
  joint_limits_lower: [-6.2832, -6.2832, -6.2832, -6.2832, -6.2832, -6.2832]
  joint_limits_upper: [6.2832, 6.2832, 6.2832, 6.2832, 6.2832, 6.2832]
