# @package ros_node

_target_: praxis.ros.robot_node.RobotNodeConfig
update_rate: 20.0
joint_state_topic: "joint_state"
ee_pose_topic: "ee_pose"
joint_command_topic: "joint_command"
ee_command_topic: "ee_command"
estop_topic: "estop"
status_topic: "robot_status"
control_mode: "ee_pose"
